function testInvalid (){
    try{
        int a = 10;
    } catch (exception e){
        exception e = {};
        int b = 10;
    }
}
